[package]
name = "tq"
version = "0.1.0"
authors = ["Brandon Slinkard <brandon.slinkard@nelnet.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
toml = "0.5.7"