name: Update Homebrew Formula

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - "main"

# TODO: Adjust this to published releases
# on: push
# release:
#   types: [published]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup variables
        run: |
          export APP_VERSION=$(cat Cargo.toml| grep version -m 1 | awk -F '"' '{ print $2 }')
          echo "::set-env name=APP_VERSION::$APP_VERSION"

      - name: Build Binaries
        run: |
          cargo build --release
          tar -czf .arbor/tq-mac.tar.gz ./target/release/tq
          echo "::set-env name=SHA256::$(shasum -a 256 .arbor/tq-mac.tar.gz | awk '{ print $1 }')"

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.APP_VERSION }}-${{ github.run_number }}
          release_name: Release ${{ env.APP_VERSION }}
          body: |
            Automated Release
          draft: false
          prerelease: false

      - name: Upload Release Assets to Github
        id: upload_release_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./.arbor/tq-mac.tar.gz
          asset_name: tq-mac.tar.gz
          asset_content_type: application/gzip

      - name: Homebrew Release
        id: create-homebrew-release
        run: |
          git config user.name "Arbor Bot"
          git config user.email "noreply@arbor.dev"
          mkdir ~/.ssh && touch ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" >> ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          git clone git@github.com:4rbor/homebrew-tq.git && rm homebrew-tq/Formula/tq.rb
          mv support/homebrew-formula.rb homebrew-tq/Formula/tq.rb
          pwd && ls
          cd homebrew-tq
          pwd && ls
          sed -i "s@_tarball_@${{ steps.upload_release_assets.outputs.browser_download_url }}@" ./Formula/tq.rb
          sed -i "s@_sha256_@$SHA256@" ./Formula/tq.rb
          sed -i "s@_version_@$APP_VERSION@" ./Formula/tq.rb
          cat Formula/tq.rb
          git add .
          git commit -m "Update to version: $APP_VERSION"
          git push
