name: Update Homebrew Formula

on:
  push:
    branches:
      - "main"

# TODO: Adjust this to published releases
# on: push
# release:
#   types: [published]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated Release
          draft: false
          prerelease: false

  # homebrew-release:
  #   runs-on: macos-latest
  #   steps:
  # - name: Release Homebrew Formula
  #   if: github.event.release.prerelease != true
  #   uses: garden-io/update-homebrew-action@v1
  #   with:
  #     packageName: "tq"
  #     templatePath: "support/homebrew-formula.rb"
  #     tapRepo: "4rbor/homebrew-tq"
  #     srcRepo: "4rbor/tq"
  #     authToken: ${{ secrets.AUTH_TOKEN }}

  #     # cargo build --release
  #     # tar -czf .arbor/tq-mac.tar.gz ./target/release/tq
  #     sed -i "" "s/{{tarball}}/test/" support/homebrew-formula.rb

  # VER=$(cat Cargo.toml| grep version -m 1 | awk -F '"' '{ print $2 }')
  # git clone git@github.com:4rbor/homebrew-tq.git
  # rm homebrew-tq/Formula/tq.rb
  # cp tq.rb homebrew-tq/Formula/tq.rb
  # cd homebrew-tq
  # git add -A
  # git commit -m "Update to version: $VER"
  # git push
